apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres
  namespace: auth

spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  template:
    metadata:
      labels:
        app: auth-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
           - name: auth-db
             valueFrom:
              configMapKeyRef:
               name: auth-configmap
               key: POSTGRES_DB

           - name: db-hsot
             valueFrom:
              configMapKeyRef:
               name: auth-configmap
               key: DB_HOST

           - name: DB-port
             valueFrom:
              configMapKeyRef:
               name: auth-configmap
               key: DB_PORT

           - name: POSTGRES_USER
             valueFrom:
              secretKeyRef:
               name : auth-secret
               key: POSTGRES_USER

           - name: POSTGRES_password
             valueFrom:
              secretKeyRef:
               name: auth-secret
               key:  POSTGRES_PASSWORD
             
            

