apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-postgres
  namespace: catalog
  labels:
    app: catalog-db

spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-db

  template:
    metadata:
      labels:
        app: catalog-db

    spec:
      containers:
        - name: catalog-postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: catalog-configmap
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: catalog-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-secret
                  key: POSTGRES_PASSWORD
